### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mstancamp** [BetterCloud/vault-java-driver#158]
Running an application hosted in a WebSphere Liberty runtime. The application uses the Vault driver to communicate with a remote Vault server. In some environments there is a need to go through a proxy to get to the Vault server. We have tried configuring the Liberty runtime with the appropriate JVM properties such as the following:
https.proxyHost
http.proxyHost
http.proxyPort
https.proxyPort
http.nonProxyHosts
But the request by the Vault driver code times out with the following error:
com.bettercloud.vault.VaultException: com.bettercloud.vault.rest.RestException: java.net.ConnectException: 

Connection timed out (Connection timed out)
[2/20/19 3:00:35:668 UTC] 0000005a SystemErr                                                    R 	at com.bettercloud.vault.api.Auth.loginByAppRole(Auth.java:348)

We can use curl on this system to successfully connect to Vault by specifying the proxy. 
Does the Vault driver have a known limitation when using a proxy? Is there some configuration that could be specified to support a proxy?

**Comment by premkashyap** [comment]
I'm also facing a similar issue. In my case gitlab access the vault through a proxy. But I'm getting below error:

Unable to load application.groovy: com.bettercloud.vault.rest.RestException: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"

    com.bettercloud.vault.VaultException: com.bettercloud.vault.rest.RestException: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
    	at com.bettercloud.vault.api.Auth.loginByAppID(Auth.java:336)
    	at com.bettercloud.vault.api.Auth$loginByAppID.call(Unknown Source)
    	at com.fanatics.badger.infarstructure.VaultClient.login(VaultClient.groovy:48)
    	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)

I tried changing the git setting to use non-proxy using -Dhttps.nonProxyHosts=.<vault domain name>.com. But still facing the same issue. 

Any help will be appreciated ?

**Comment by ymurong** [comment]
According to the documentation, proxy is not yet supported. 

> the proxy settings may return in a future version, but it's too misleading to have methods exposed for settings that won't really be supported soon

So I bet for now we have to call directly vault api with our own httpclient, but it will be interesting if this feature could be added to roadmap.

**Comment by stephenc** [comment]
You can currently direct `Vault` to use a proxy... but you'll feel dirty afterwards!

You need to call `java.net.ProxySelector.setDefault(...)` and supply a proxy selector... if your proxy requires authentication then you may have to call `java.net.Authenticator.setDefault(...)`

Good luck with race conditions if you need to swap the implementations in and out as these are JVM singletons.

Good look with the security manager if running in a servlet container that applies a security policy

I have created #191 with my suggested API changes to make this something that consumers can control... TBD the reaction to that

**Comment by stephenc** [comment]
I needed a released jar with proxy support and there were time constraints that couldn’t be met from an OSS project such as this one.
I have released a *temporary* fork that others can use until this issue gets resolved. I have put as big a warning sign on the fork as I can. The groupId even includes `tmp-fork`. https://search.maven.org/artifact/io.github.stephenc.tmp-fork/vault-java-driver/4.2.0/jar

I will not be maintaining my temporary fork other than my own needs. The intent is that the only difference is the additional proxy specification methods, otherwise identical to the upstream here. The fork will be discontinued once upstream has a solution to the proxy problem (I don’t mind what the solution is as long as it doesn’t require installation of a JVM global proxy selector. My PR is one possible path).

**Comment by adammead** [comment]
Is PR #191 going to be approved/merged sometime? We've found that we need the change as well.
