### ISSUE TITLE
Getting protocol_version error 

### ISSUE THREAD

**Issue by adityagu0910** [BetterCloud/vault-java-driver#206]
I am getting below error, any suggestions what could be the reason .
I checked from URL, i am getting protocol as TLSv1.2
SSL-Session:
    Protocol  : TLSv1.2

`[14/01/20 15:15:39:663 EST] 00000069 SystemErr     R com.bettercloud.vault.VaultException: com.bettercloud.vault.rest.RestException: javax.net.ssl.SSLException: Received fatal alert: protocol_version
[14/01/20 15:15:39:664 EST] 00000069 SystemErr     R 	at com.bettercloud.vault.api.pki.Pki.issue(Pki.java:493)
[14/01/20 15:15:39:664 EST] 00000069 SystemErr     R 	at com.bettercloud.vault.api.pki.Pki.issue(Pki.java:377)
[14/01/20 15:15:39:668 EST] 00000069 SystemErr     R 	at com.bettercloud.vault.rest.Rest.postOrPutImpl(Rest.java:416)
[14/01/20 15:15:39:668 EST] 00000069 SystemErr     R 	at com.bettercloud.vault.rest.Rest.post(Rest.java:306)
[14/01/20 15:15:39:668 EST] 00000069 SystemErr     R 	at com.bettercloud.vault.api.pki.Pki.issue(Pki.java:471)
[14/01/20 15:15:39:668 EST] 00000069 SystemErr     R 	... 39 more
[14/01/20 15:15:39:668 EST] 00000069 SystemErr     R Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version`

**Comment by adityagu0910** [comment]
after enabling TLSv1.2 on server side above error is gone.
I am getting below exception now 

`	java.security.cert.CertPathValidatorException: Certificate chaining error
[15/01/20 9:47:46:200 EST] 00000072 SystemErr     R 	at com.bettercloud.vault.api.pki.Pki.issue(Pki.java:493)
[15/01/20 9:47:46:200 EST] 00000072 SystemErr     R 	at com.bettercloud.vault.api.pki.Pki.issue(Pki.java:377)`

**Comment by adityagu0910** [comment]
It worked for me after adding my root cert to server truststore
