### ISSUE TITLE
Unable to run the new integrationTest suite on MacOS

### ISSUE THREAD

**Issue by brianmcfeeley** [BetterCloud/vault-java-driver#68]
Hi there!

I've forked this repo to extend the API endpoint coverage to `sys/policy` for getting/creating policies, but I'm having trouble running 3.0.0's integration test suite. I have a strong feeling that the problem may be PEBKAC but I wanted to bring it to your attention in the event that I'm wrong.

Here's an example stack trace that I'm seeing:
```
17:26:19.664 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor] Executing test class com.bettercloud.vault.api.AuthBackendAppRoleTests
17:26:14.533 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor] 
> Task :integrationTest
17:26:19.660 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
17:26:19.660 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     EnvironmentAndSystemPropertyClientProviderStrategy: failed with exception ExceptionInInitializerError (null). Root cause IllegalStateException (Only supported on Linux)
17:26:19.660 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (this strategy is only applicable to Linux)
17:26:19.661 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     ProxiedUnixSocketClientProviderStrategy: failed with exception IllegalArgumentException (Socket file does not exist: /var/run/docker.sock)
17:26:19.661 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     DockerMachineClientProviderStrategy: failed with exception InvalidConfigurationException (Exception when executing docker-machine status )
17:26:19.662 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     WindowsClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause ConnectException (Connection refused: localhost/127.0.0.1:2375)
17:26:19.662 [DEBUG] [TestEventLogger]     [Test worker] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
17:26:19.664 [DEBUG] [TestEventLogger] 
17:26:19.664 [DEBUG] [TestEventLogger] com.bettercloud.vault.api.AuthBackendAppIdTests > classMethod STARTED
17:26:19.692 [DEBUG] [TestEventLogger] 
17:26:19.692 [DEBUG] [TestEventLogger] com.bettercloud.vault.api.AuthBackendAppIdTests > classMethod FAILED
17:26:19.692 [DEBUG] [TestEventLogger]     java.lang.ExceptionInInitializerError
17:26:19.692 [DEBUG] [TestEventLogger]         at sun.misc.Unsafe.ensureClassInitialized(Native Method)
17:26:19.692 [DEBUG] [TestEventLogger]         at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
17:26:19.692 [DEBUG] [TestEventLogger]         at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
17:26:19.692 [DEBUG] [TestEventLogger]         at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
17:26:19.692 [DEBUG] [TestEventLogger]         at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
17:26:19.692 [DEBUG] [TestEventLogger]         at java.lang.reflect.Field.get(Field.java:393)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
17:26:19.692 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:26:19.692 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:26:19.692 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:26:19.692 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
17:26:19.692 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
17:26:19.693 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
17:26:19.693 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:26:19.693 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:26:19.693 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:26:19.693 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
17:26:19.693 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17:26:19.693 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17:26:19.693 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
17:26:19.693 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
17:26:19.693 [DEBUG] [TestEventLogger] 
17:26:19.693 [DEBUG] [TestEventLogger]         Caused by:
17:26:19.693 [DEBUG] [TestEventLogger]         java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
17:26:19.693 [DEBUG] [TestEventLogger]             at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:90)
17:26:19.693 [DEBUG] [TestEventLogger]             at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:83)
17:26:19.693 [DEBUG] [TestEventLogger]             at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:111)
17:26:19.693 [DEBUG] [TestEventLogger]             at com.bettercloud.vault.api.VaultContainer.<init>(VaultContainer.java:105)
17:26:19.693 [DEBUG] [TestEventLogger]             at com.bettercloud.vault.api.AuthBackendAppIdTests.<clinit>(AuthBackendAppIdTests.java:18)
17:26:19.693 [DEBUG] [TestEventLogger]             ... 41 more
17:26:19.694 [DEBUG] [TestEventLogger] 
17:26:19.694 [DEBUG] [TestEventLogger] com.bettercloud.vault.api.AuthBackendAppIdTests FAILED
```

I did some browsing of TestContainer issues for similar stuff, and it looked like a similar problem was resolved for those who made sure `docker-machine` was available on their path. I confirmed both `docker` and `docker-machine` are available:

```
bmcfeeley-rMBP:vault-java-driver bmcfeeley$ which docker
/usr/local/bin/docker
bmcfeeley-rMBP:vault-java-driver bmcfeeley$ which docker-machine
/usr/local/bin/docker-machine
```

I couldn't find any more docs to see if I'm missing some setup or configuration piece of the puzzle so I thought I'd give you a shout.

Hope you have a nice weekend!

**Comment by brianmcfeeley** [comment]
Looks like PEBKAC indeed -- I didn't have a docker machine set up on my new laptop. I'm gonna close this for now since the vault server appears to be standing up the way we'd expect.

**Comment by steve-perkins** [comment]
Sorry for the delayed response, I'm currently off on vacation.  Glad that the test suite is working on your environment!
